### PR TITLE
Collections Functionality

### PR DESCRIPTION
**Pull request by Jacob411**
# Collection Document Management Enhancement

## Overview
This PR adds comprehensive document management capabilities to collections, allowing users to view, add, and remove documents from their collections through an intuitive interface.

### New Features
- Added document management modal for collections
- Implemented multi-document selection and bulk adding capability
- Added quick document removal from collections
- Made document counts clickable to view collection contents
- Added slide-out document selection interface

### New Components
- `CollectionDocuments.tsx`: A reusable component for managing documents within collections
  - Shows detailed document information in a table view
  - Provides document addition via a slide-out sheet
  - Supports document removal with immediate UI updates
  - Maintains consistent styling with the main dashboard

### UI/UX Improvements
- Interactive document count in collections table
- Visual feedback for document status and actions
- Consistent loading states and error handling
- Responsive layout for all screen sizes
- Maintains dark mode compatibility

### Technical Details
- Uses ShadcnUI components for consistent styling
- Implements optimistic updates for better UX
- Handles API interactions with proper error boundaries
- Maintains state synchronization between components
- Uses TypeScript for type safety

## Required Changes
- Install additional ShadcnUI components:
  ```bash
  npx shadcn-ui@latest add sheet
  npx shadcn-ui@latest add scroll-area
  npx shadcn-ui@latest add checkbox

### CODE REVIEW

**Comment by owenstrength** [comment]
image

the actions bar goes off of the modal

**Comment by owenstrength** [comment]
image

not sure how I feel about this on the side bar.

also the close and add documents button seem a bit high up on the page

**Comment by Jacob411** [comment]
Yes I don’t like the ui. Gonna make it nicer

**Comment by Jacob411** [comment]
Made some changes:
- restructured Collections
- changed ui to a dropdown format
- took away some of the larger buttons in favor of ghost icons

**Pull request merged**
